//! `insmod`/`rmmod`/`lsmod`/`modprobe` — real kernel module management via
//! the `kmod` crate's FFI bindings to the system's real `libkmod.so`
//! (Arch's real `kmod` package), the same "delegate to the real system
//! library rather than reimplement its logic" choice this project already
//! made for password hashing (`crypt(3)`) and file-type detection
//! (`libmagic`). `modprobe`'s own real value is dependency/alias
//! resolution (walking a real `modules.dep`/`modules.alias`, generated by
//! `depmod` from the real per-module `.ko` metadata) — genuinely complex
//! logic not worth re-deriving when `libkmod` already implements it
//! correctly and this project can just call it.
//!
//! Scope: `insmod FILE [params...]` (load one exact `.ko` file, no
//! dependency resolution — matches real `insmod`), `rmmod NAME...` (remove
//! by name, no dependency awareness — matches real `rmmod`), `lsmod` (real
//! `/proc/modules`-derived listing, same column layout as real `lsmod`),
//! `modprobe [-r] NAME [params...]` (alias/dependency-resolved load or
//! remove, `libkmod`'s actual job).
//!
//! Not implemented: `modprobe -a` (multiple module args), `-b`/`-q`/`-v`/
//! `-n`/`-c`/`-l`/`--dump-modversions`, `/etc/modprobe.d` config
//! directives (blacklist/install/remove commands — `libkmod` itself reads
//! these from its own config search path, so blacklists etc. do apply,
//! just not this tool's own flags for overriding them).
//!
//! Not exercised end to end in the boot test: this dev machine has no
//! kernel headers matching its own running kernel (`linux-headers` isn't
//! installed), so there's no way to build a real loadable `.ko` to prove
//! an actual insert/remove cycle — same category of environment gap as
//! `makepkg-rs`'s still-open PGP keyserver import. `lsmod` and the
//! error-path behavior of `insmod`/`rmmod`/`modprobe` against a name that
//! genuinely doesn't exist are still verified for real, since both
//! exercise the real `libkmod` FFI calls, just not a successful load.

use std::ffi::OsString;
use std::vec::IntoIter;

fn ctx() -> Result<kmod::Context, i32> {
    kmod::Context::new().map_err(|e| {
        eprintln!("kmod: could not open libkmod context: {e}");
        1
    })
}

pub fn run_lsmod(_args: IntoIter<OsString>) -> i32 {
    let ctx = match kmod::Context::new() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("lsmod: could not open libkmod context: {e}");
            return 1;
        }
    };
    let modules = match ctx.modules_loaded() {
        Ok(m) => m,
        Err(e) => {
            eprintln!("lsmod: {e}");
            return 1;
        }
    };
    println!("{:<19}{:>9}  Used by", "Module", "Size");
    for module in modules {
        let name = module.name().to_string_lossy();
        let size = module.size();
        let refcount = module.refcount();
        let holders: Vec<String> = module
            .holders()
            .map(|h| h.name().to_string_lossy().into_owned())
            .collect();
        if holders.is_empty() {
            println!("{name:<19}{size:>9}  {refcount}");
        } else {
            println!("{name:<19}{size:>9}  {refcount} {}", holders.join(","));
        }
    }
    0
}

pub fn run_insmod(mut args: IntoIter<OsString>) -> i32 {
    args.next(); // argv[0]: our own utility name
    let Some(path) = args.next() else {
        eprintln!("insmod: usage: insmod FILE [module options...]");
        return 1;
    };
    let opts: Vec<String> = args.map(|a| a.to_string_lossy().into_owned()).collect();
    let opt_refs: Vec<&str> = opts.iter().map(String::as_str).collect();

    let ctx = match ctx() {
        Ok(c) => c,
        Err(code) => return code,
    };
    let module = match ctx.module_new_from_path(&path) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("insmod: could not open '{}': {e}", path.to_string_lossy());
            return 1;
        }
    };
    if let Err(e) = module.insert_module(0, &opt_refs) {
        eprintln!(
            "insmod: could not insert module {}: {e}",
            path.to_string_lossy()
        );
        return 1;
    }
    0
}

pub fn run_rmmod(mut args: IntoIter<OsString>) -> i32 {
    args.next(); // argv[0]: our own utility name
    let names: Vec<String> = args.map(|a| a.to_string_lossy().into_owned()).collect();
    if names.is_empty() {
        eprintln!("rmmod: usage: rmmod MODULE...");
        return 1;
    }
    let ctx = match ctx() {
        Ok(c) => c,
        Err(code) => return code,
    };
    let mut status = 0;
    for name in names {
        match ctx
            .module_new_from_name(&name)
            .and_then(|m| m.remove_module(0))
        {
            Ok(()) => {}
            Err(e) => {
                eprintln!("rmmod: could not remove '{name}': {e}");
                status = 1;
            }
        }
    }
    status
}

pub fn run_modprobe(mut args: IntoIter<OsString>) -> i32 {
    args.next(); // argv[0]: our own utility name
    let mut remove = false;
    let mut name = None;
    let mut opts = Vec::new();
    for arg in args {
        match arg.to_str() {
            Some("-r") | Some("--remove") => remove = true,
            _ if name.is_none() => name = Some(arg.to_string_lossy().into_owned()),
            _ => opts.push(arg.to_string_lossy().into_owned()),
        }
    }
    let Some(name) = name else {
        eprintln!("modprobe: usage: modprobe [-r] MODULE [module options...]");
        return 1;
    };

    let ctx = match ctx() {
        Ok(c) => c,
        Err(code) => return code,
    };
    let modules = match ctx.module_new_from_lookup(&name) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("modprobe: could not resolve '{name}': {e}");
            return 1;
        }
    };
    let mut found = false;
    let opt_refs: Vec<&str> = opts.iter().map(String::as_str).collect();
    for module in modules {
        found = true;
        let result = if remove {
            module.remove_module(0)
        } else {
            module.insert_module(0, &opt_refs)
        };
        // Real modprobe treats "already inserted"/"not currently inserted"
        // as success, not an error — the same idempotent semantics
        // systemd/initramfs scripts rely on.
        let already_done = match &result {
            Err(kmod::Error::InsertModule(errno)) if !remove => errno.0 == libc::EEXIST,
            Err(kmod::Error::RemoveModule(errno)) if remove => errno.0 == libc::ENOENT,
            _ => false,
        };
        if let Err(e) = result
            && !already_done
        {
            eprintln!(
                "modprobe: could not {} '{name}': {e}",
                if remove { "remove" } else { "insert" }
            );
            return 1;
        }
    }
    if !found {
        eprintln!("modprobe: module '{name}' not found");
        return 1;
    }
    0
}
