//! A busybox/uutils-style multicall binary: reimplementing every individual
//! coreutils command from scratch would just re-derive `uutils/coreutils`,
//! which ROADMAP.md already calls out as prior art to adapt rather than
//! reinvent. So this crate vendors the real `uu_*` crates (the same ones
//! the upstream `coreutils` multicall binary is built from) and supplies
//! only the dispatch logic: pick a utility by name and hand it argv, same
//! as busybox does for its applets.
//!
//! Every `uu_*` crate's public `uumain` is generated by the `#[uucore::main]`
//! attribute macro into `fn(impl uucore::Args) -> i32`, which already
//! prints errors and computes the exit code — there's no `Result` for this
//! binary to unwrap, just an exit code to forward.
//!
//! Two calling conventions, both matching real coreutils/busybox behavior:
//! - as a symlink named after the utility (`ls -> coreutils-rs`, argv[0]
//!   is `ls`) — the common way to actually install this as a system's
//!   userland
//! - as `coreutils-rs <utility> [args...]` — useful for trying it out
//!   without installing symlinks first

use std::ffi::OsString;
use std::process::ExitCode;
use std::vec::IntoIter;

mod grep_cmd;
mod gzip_cmd;
mod sed_cmd;
mod tar_cmd;

include!("util_list.rs");

/// findutils (GNU findutils' Rust port) predates and doesn't share
/// coreutils' `#[uucore::main]`-generated `fn(impl Args) -> i32` shape:
/// its entry points take `&[&str]` directly, and `find_main` additionally
/// wants a `Dependencies` object (stdio/filesystem access, used upstream
/// to let `find`'s own test suite mock them out).
fn run_findutils_str_args(args: IntoIter<OsString>) -> Vec<String> {
    args.map(|s| s.to_string_lossy().into_owned()).collect()
}

fn dispatch(name: &str, args: IntoIter<OsString>) -> Option<i32> {
    Some(match name {
        "ls" => uu_ls::uumain(args),
        "cat" => uu_cat::uumain(args),
        "cp" => uu_cp::uumain(args),
        "mv" => uu_mv::uumain(args),
        "rm" => uu_rm::uumain(args),
        "mkdir" => uu_mkdir::uumain(args),
        "echo" => uu_echo::uumain(args),
        "pwd" => uu_pwd::uumain(args),
        "touch" => uu_touch::uumain(args),
        "wc" => uu_wc::uumain(args),
        "head" => uu_head::uumain(args),
        "tail" => uu_tail::uumain(args),
        "true" => uu_true::uumain(args),
        "false" => uu_false::uumain(args),
        "chmod" => uu_chmod::uumain(args),
        "chown" => uu_chown::uumain(args),
        "chgrp" => uu_chgrp::uumain(args),
        "ln" => uu_ln::uumain(args),
        "rmdir" => uu_rmdir::uumain(args),
        "mkfifo" => uu_mkfifo::uumain(args),
        "mknod" => uu_mknod::uumain(args),
        "du" => uu_du::uumain(args),
        "df" => uu_df::uumain(args),
        "sort" => uu_sort::uumain(args),
        "uniq" => uu_uniq::uumain(args),
        "cut" => uu_cut::uumain(args),
        "tr" => uu_tr::uumain(args),
        "tee" => uu_tee::uumain(args),
        "dd" => uu_dd::uumain(args),
        "dirname" => uu_dirname::uumain(args),
        "basename" => uu_basename::uumain(args),
        "realpath" => uu_realpath::uumain(args),
        "readlink" => uu_readlink::uumain(args),
        "sync" => uu_sync::uumain(args),
        "sleep" => uu_sleep::uumain(args),
        "date" => uu_date::uumain(args),
        "id" => uu_id::uumain(args),
        "whoami" => uu_whoami::uumain(args),
        "who" => uu_who::uumain(args),
        "uname" => uu_uname::uumain(args),
        "env" => uu_env::uumain(args),
        "printf" => uu_printf::uumain(args),
        "seq" => uu_seq::uumain(args),
        "shuf" => uu_shuf::uumain(args),
        "split" => uu_split::uumain(args),
        "join" => uu_join::uumain(args),
        "paste" => uu_paste::uumain(args),
        "comm" => uu_comm::uumain(args),
        "expand" => uu_expand::uumain(args),
        "unexpand" => uu_unexpand::uumain(args),
        "fold" => uu_fold::uumain(args),
        "fmt" => uu_fmt::uumain(args),
        "nl" => uu_nl::uumain(args),
        "od" => uu_od::uumain(args),
        "base64" => uu_base64::uumain(args),
        "base32" => uu_base32::uumain(args),
        "md5sum" => uu_md5sum::uumain(args),
        "sha1sum" => uu_sha1sum::uumain(args),
        "sha256sum" => uu_sha256sum::uumain(args),
        "sha512sum" => uu_sha512sum::uumain(args),
        "mktemp" => uu_mktemp::uumain(args),
        "install" => uu_install::uumain(args),
        "stat" => uu_stat::uumain(args),
        "test" | "[" => uu_test::uumain(args),
        "expr" => uu_expr::uumain(args),
        "yes" => uu_yes::uumain(args),
        "nice" => uu_nice::uumain(args),
        "nohup" => uu_nohup::uumain(args),
        "timeout" => uu_timeout::uumain(args),
        "kill" => uu_kill::uumain(args),
        "factor" => uu_factor::uumain(args),
        "numfmt" => uu_numfmt::uumain(args),
        "tsort" => uu_tsort::uumain(args),
        "csplit" => uu_csplit::uumain(args),
        "shred" => uu_shred::uumain(args),
        "link" => uu_link::uumain(args),
        "unlink" => uu_unlink::uumain(args),
        "vdir" => uu_vdir::uumain(args),
        "dir" => uu_dir::uumain(args),
        "dircolors" => uu_dircolors::uumain(args),
        "groups" => uu_groups::uumain(args),
        "logname" => uu_logname::uumain(args),
        "tty" => uu_tty::uumain(args),
        "users" => uu_users::uumain(args),
        "stdbuf" => uu_stdbuf::uumain(args),
        "hostid" => uu_hostid::uumain(args),
        "arch" => uu_arch::uumain(args),
        "nproc" => uu_nproc::uumain(args),
        "printenv" => uu_printenv::uumain(args),
        "pathchk" => uu_pathchk::uumain(args),
        "pinky" => uu_pinky::uumain(args),
        "sum" => uu_sum::uumain(args),
        "cksum" => uu_cksum::uumain(args),
        "find" => {
            let owned = run_findutils_str_args(args);
            let strs: Vec<&str> = owned.iter().map(String::as_str).collect();
            let deps = findutils::find::StandardDependencies::new();
            findutils::find::find_main(&strs, &deps)
        }
        "xargs" => {
            let owned = run_findutils_str_args(args);
            let strs: Vec<&str> = owned.iter().map(String::as_str).collect();
            findutils::xargs::xargs_main(&strs)
        }
        "locate" => {
            let owned = run_findutils_str_args(args);
            let strs: Vec<&str> = owned.iter().map(String::as_str).collect();
            findutils::locate::locate_main(&strs)
        }
        "updatedb" => {
            let owned = run_findutils_str_args(args);
            let strs: Vec<&str> = owned.iter().map(String::as_str).collect();
            findutils::updatedb::updatedb_main(&strs)
        }
        "tar" => tar_cmd::run(args),
        "grep" => grep_cmd::run(args),
        "sed" => sed_cmd::run(args),
        "gzip" => gzip_cmd::run(args),
        "gunzip" => gzip_cmd::run_gunzip(args),
        "zcat" => gzip_cmd::run_zcat(args),
        _ => return None,
    })
}

fn utility_names() -> String {
    UTILS
        .iter()
        .map(|(name, _)| *name)
        .collect::<Vec<_>>()
        .join(", ")
}

/// `dir`/`vdir` are thin wrappers around `ls`'s own logic and ship no
/// locale files of their own — real coreutils resolves their Fluent
/// strings from `ls`'s bundle instead (see `uucore::get_canonical_util_name`,
/// which does this same `uu_<name>` → canonical-name mapping for the
/// per-utility binaries in the actual uutils/coreutils monorepo).
fn setup_locale_for(util: &str) {
    let crate_name = UTILS
        .iter()
        .find(|(name, _)| *name == util)
        .map_or(util, |(_, crate_name)| crate_name);
    // Non-uucore-based utilities (e.g. findutils) have no "uu_" prefix to
    // strip and no Fluent locale bundle to look for in the first place.
    if !crate_name.starts_with("uu_") {
        return;
    }
    let canonical = uucore::get_canonical_util_name(crate_name);
    let _ = uucore::locale::setup_localization(canonical);
}

fn main() -> ExitCode {
    let argv: Vec<OsString> = std::env::args_os().collect();
    let exe_name = argv
        .first()
        .and_then(|a| std::path::Path::new(a).file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("coreutils-rs")
        .to_string();

    // Symlink form: argv[0] is already the utility name (e.g. `ls`).
    if UTILS.iter().any(|(name, _)| *name == exe_name) {
        setup_locale_for(&exe_name);
        if let Some(code) = dispatch(&exe_name, argv.clone().into_iter()) {
            return exit_code(code);
        }
    }

    // `coreutils-rs <utility> [args...]` form: argv[1] names the utility,
    // and it's handed to the sub-uumain as its own argv[0] so the
    // utility's usage/error messages read as if it were invoked directly.
    let util = argv.get(1).and_then(|a| a.to_str()).map(str::to_string);
    if let Some(util) = util {
        uucore::set_utility_is_second_arg();
        if UTILS.iter().any(|(name, _)| *name == util) {
            setup_locale_for(&util);
        }
        let sub_argv = argv.into_iter().skip(1).collect::<Vec<_>>().into_iter();
        if let Some(code) = dispatch(&util, sub_argv) {
            return exit_code(code);
        }
        eprintln!("coreutils-rs: unknown utility '{util}'");
        eprintln!("available utilities: {}", utility_names());
        return ExitCode::FAILURE;
    }

    eprintln!("usage: coreutils-rs <utility> [args...]");
    eprintln!("       (or install as a symlink named after the utility)");
    eprintln!("available utilities: {}", utility_names());
    ExitCode::FAILURE
}

fn exit_code(code: i32) -> ExitCode {
    ExitCode::from(code as u8)
}
