//! A busybox/uutils-style multicall binary: reimplementing every individual
//! coreutils command from scratch would just re-derive `uutils/coreutils`,
//! which ROADMAP.md already calls out as prior art to adapt rather than
//! reinvent. So this crate vendors the real `uu_*` crates (the same ones
//! the upstream `coreutils` multicall binary is built from) and supplies
//! only the dispatch logic: pick a utility by name and hand it argv, same
//! as busybox does for its applets.
//!
//! Every `uu_*` crate's public `uumain` is generated by the `#[uucore::main]`
//! attribute macro into `fn(impl uucore::Args) -> i32`, which already
//! prints errors and computes the exit code — there's no `Result` for this
//! binary to unwrap, just an exit code to forward.
//!
//! Two calling conventions, both matching real coreutils/busybox behavior:
//! - as a symlink named after the utility (`ls -> coreutils-rs`, argv[0]
//!   is `ls`) — the common way to actually install this as a system's
//!   userland
//! - as `coreutils-rs <utility> [args...]` — useful for trying it out
//!   without installing symlinks first

use std::ffi::OsString;
use std::os::unix::process::CommandExt;
use std::process::ExitCode;
use std::vec::IntoIter;

mod awk_cmd;
mod column_cmd;
mod curl_cmd;
mod diff_cmd;
mod dmesg_cmd;
mod file_cmd;
mod grep_cmd;
mod gzip_cmd;
mod ip_cmd;
mod less_cmd;
mod lsblk_cmd;
mod lspci_cmd;
mod lsusb_cmd;
mod mount_cmd;
mod patch_cmd;
mod ping_cmd;
mod procps_cmd;
mod sed_cmd;
mod ss_cmd;
mod tar_cmd;
mod which_cmd;

include!("util_list.rs");

/// findutils (GNU findutils' Rust port) predates and doesn't share
/// coreutils' `#[uucore::main]`-generated `fn(impl Args) -> i32` shape:
/// its entry points take `&[&str]` directly, and `find_main` additionally
/// wants a `Dependencies` object (stdio/filesystem access, used upstream
/// to let `find`'s own test suite mock them out).
fn run_findutils_str_args(args: IntoIter<OsString>) -> Vec<String> {
    args.map(|s| s.to_string_lossy().into_owned()).collect()
}

fn dispatch(name: &str, args: IntoIter<OsString>) -> Option<i32> {
    Some(match name {
        "ls" => uu_ls::uumain(args),
        "cat" => uu_cat::uumain(args),
        "cp" => uu_cp::uumain(args),
        "mv" => uu_mv::uumain(args),
        "rm" => uu_rm::uumain(args),
        "mkdir" => uu_mkdir::uumain(args),
        "echo" => uu_echo::uumain(args),
        "pwd" => uu_pwd::uumain(args),
        "touch" => uu_touch::uumain(args),
        "wc" => uu_wc::uumain(args),
        "head" => uu_head::uumain(args),
        "tail" => uu_tail::uumain(args),
        "true" => uu_true::uumain(args),
        "false" => uu_false::uumain(args),
        "chmod" => uu_chmod::uumain(args),
        "chown" => uu_chown::uumain(args),
        "chgrp" => uu_chgrp::uumain(args),
        "ln" => uu_ln::uumain(args),
        "rmdir" => uu_rmdir::uumain(args),
        "mkfifo" => uu_mkfifo::uumain(args),
        "mknod" => uu_mknod::uumain(args),
        "du" => uu_du::uumain(args),
        "df" => uu_df::uumain(args),
        "sort" => uu_sort::uumain(args),
        "uniq" => uu_uniq::uumain(args),
        "cut" => uu_cut::uumain(args),
        "tr" => uu_tr::uumain(args),
        "tee" => uu_tee::uumain(args),
        "dd" => uu_dd::uumain(args),
        "dirname" => uu_dirname::uumain(args),
        "basename" => uu_basename::uumain(args),
        "realpath" => uu_realpath::uumain(args),
        "readlink" => uu_readlink::uumain(args),
        "sync" => uu_sync::uumain(args),
        "sleep" => uu_sleep::uumain(args),
        "date" => uu_date::uumain(args),
        "id" => uu_id::uumain(args),
        "whoami" => uu_whoami::uumain(args),
        "who" => uu_who::uumain(args),
        "uname" => uu_uname::uumain(args),
        "env" => uu_env::uumain(args),
        "printf" => uu_printf::uumain(args),
        "seq" => uu_seq::uumain(args),
        "shuf" => uu_shuf::uumain(args),
        "split" => uu_split::uumain(args),
        "join" => uu_join::uumain(args),
        "paste" => uu_paste::uumain(args),
        "comm" => uu_comm::uumain(args),
        "expand" => uu_expand::uumain(args),
        "unexpand" => uu_unexpand::uumain(args),
        "fold" => uu_fold::uumain(args),
        "fmt" => uu_fmt::uumain(args),
        "nl" => uu_nl::uumain(args),
        "od" => uu_od::uumain(args),
        "base64" => uu_base64::uumain(args),
        "base32" => uu_base32::uumain(args),
        "md5sum" => uu_md5sum::uumain(args),
        "sha1sum" => uu_sha1sum::uumain(args),
        "sha256sum" => uu_sha256sum::uumain(args),
        "sha512sum" => uu_sha512sum::uumain(args),
        "mktemp" => uu_mktemp::uumain(args),
        "install" => uu_install::uumain(args),
        "stat" => uu_stat::uumain(args),
        "test" | "[" => uu_test::uumain(args),
        "expr" => uu_expr::uumain(args),
        "yes" => uu_yes::uumain(args),
        "nice" => uu_nice::uumain(args),
        "nohup" => uu_nohup::uumain(args),
        "timeout" => uu_timeout::uumain(args),
        "kill" => uu_kill::uumain(args),
        "factor" => uu_factor::uumain(args),
        "numfmt" => uu_numfmt::uumain(args),
        "tsort" => uu_tsort::uumain(args),
        "csplit" => uu_csplit::uumain(args),
        "shred" => uu_shred::uumain(args),
        "link" => uu_link::uumain(args),
        "unlink" => uu_unlink::uumain(args),
        "vdir" => uu_vdir::uumain(args),
        "dir" => uu_dir::uumain(args),
        "dircolors" => uu_dircolors::uumain(args),
        "groups" => uu_groups::uumain(args),
        "logname" => uu_logname::uumain(args),
        "tty" => uu_tty::uumain(args),
        "users" => uu_users::uumain(args),
        "stdbuf" => uu_stdbuf::uumain(args),
        "hostid" => uu_hostid::uumain(args),
        "arch" => uu_arch::uumain(args),
        "nproc" => uu_nproc::uumain(args),
        "printenv" => uu_printenv::uumain(args),
        "pathchk" => uu_pathchk::uumain(args),
        "pinky" => uu_pinky::uumain(args),
        "sum" => uu_sum::uumain(args),
        "cksum" => uu_cksum::uumain(args),
        "chroot" => uu_chroot::uumain(args),
        "hostname" => uu_hostname::uumain(args),
        "b2sum" => uu_b2sum::uumain(args),
        "basenc" => uu_basenc::uumain(args),
        "pr" => uu_pr::uumain(args),
        "sha224sum" => uu_sha224sum::uumain(args),
        "sha384sum" => uu_sha384sum::uumain(args),
        "stty" => uu_stty::uumain(args),
        "tac" => uu_tac::uumain(args),
        "truncate" => uu_truncate::uumain(args),
        "more" => uu_more::uumain(args),
        "find" => {
            let owned = run_findutils_str_args(args);
            let strs: Vec<&str> = owned.iter().map(String::as_str).collect();
            let deps = findutils::find::StandardDependencies::new();
            findutils::find::find_main(&strs, &deps)
        }
        "xargs" => {
            let owned = run_findutils_str_args(args);
            let strs: Vec<&str> = owned.iter().map(String::as_str).collect();
            findutils::xargs::xargs_main(&strs)
        }
        "locate" => {
            let owned = run_findutils_str_args(args);
            let strs: Vec<&str> = owned.iter().map(String::as_str).collect();
            findutils::locate::locate_main(&strs)
        }
        "updatedb" => {
            let owned = run_findutils_str_args(args);
            let strs: Vec<&str> = owned.iter().map(String::as_str).collect();
            findutils::updatedb::updatedb_main(&strs)
        }
        "tar" => tar_cmd::run(args),
        "grep" => grep_cmd::run(args),
        "sed" => sed_cmd::run(args),
        "less" => less_cmd::run(args),
        "gzip" => gzip_cmd::run(args),
        "gunzip" => gzip_cmd::run_gunzip(args),
        "zcat" => gzip_cmd::run_zcat(args),
        // brush_shell::entry::run() reads *real* process argv itself
        // (see the doc comment on `reexec_as` below) rather than taking
        // the `args` iterator we build for every other utility, and it
        // always calls process::exit() internally — it never returns.
        // This arm is only reachable from the symlink form, where our
        // real argv is already exactly what brush expects.
        "sh" | "bash" => {
            brush_shell::entry::run();
            unreachable!("brush_shell::entry::run() always calls process::exit")
        }
        "which" => which_cmd::run(args),
        "patch" => patch_cmd::run(args),
        "awk" => awk_cmd::run(args),
        "curl" => curl_cmd::run(args),
        "ps" => procps_cmd::run_ps(args),
        "free" => procps_cmd::run_free(args),
        "uptime" => procps_cmd::run_uptime(args),
        "file" => file_cmd::run(args),
        "ping" => ping_cmd::run(args),
        "column" => column_cmd::run(args),
        "diff" => diff_cmd::run_diff(args),
        "cmp" => diff_cmd::run_cmp(args),
        "dmesg" => dmesg_cmd::run(args),
        "mount" => mount_cmd::run_mount(args),
        "umount" => mount_cmd::run_umount(args),
        "ss" => ss_cmd::run(args),
        "ip" => ip_cmd::run(args),
        "lsblk" => lsblk_cmd::run(args),
        "lspci" => lspci_cmd::run(args),
        "lsusb" => lsusb_cmd::run(args),
        "passwd" => uu_passwd::uumain(args),
        "useradd" => uu_useradd::uumain(args),
        "userdel" => uu_userdel::uumain(args),
        "usermod" => uu_usermod::uumain(args),
        "chpasswd" => uu_chpasswd::uumain(args),
        "chage" => uu_chage::uumain(args),
        "groupadd" => uu_groupadd::uumain(args),
        "groupdel" => uu_groupdel::uumain(args),
        "groupmod" => uu_groupmod::uumain(args),
        "grpck" => uu_grpck::uumain(args),
        "pwck" => uu_pwck::uumain(args),
        "chfn" => uu_chfn::uumain(args),
        "chsh" => uu_chsh::uumain(args),
        "newgrp" => uu_newgrp::uumain(args),
        _ => return None,
    })
}

/// `brush_shell::entry::run()` (see `dispatch` above) parses `std::env
/// ::args()` itself instead of taking an args iterator, so it only works
/// correctly when our own real argv is already shaped like a normal
/// shell invocation (argv[0] = the shell's name). That's true for the
/// symlink form but not `coreutils-rs bash args...`, where argv[0] is
/// `coreutils-rs` and argv[1] is `bash` — brush would try to parse
/// "bash" as if it were a script file to run. Re-executing ourselves
/// with a corrected argv[0] (via `arg0`, distinct from the actual
/// program path) fixes this generally, for brush or anything else that
/// might someday read real argv the same way.
fn reexec_as(util: &str, rest: &[OsString]) -> ExitCode {
    let exe = match std::env::current_exe() {
        Ok(p) => p,
        Err(e) => {
            eprintln!("coreutils-rs: could not determine current executable: {e}");
            return ExitCode::FAILURE;
        }
    };
    let err = std::process::Command::new(&exe)
        .arg0(util)
        .args(rest)
        .exec();
    eprintln!("coreutils-rs: failed to re-exec as '{util}': {err}");
    ExitCode::FAILURE
}

fn utility_names() -> String {
    UTILS
        .iter()
        .map(|(name, _)| *name)
        .collect::<Vec<_>>()
        .join(", ")
}

/// `dir`/`vdir` are thin wrappers around `ls`'s own logic and ship no
/// locale files of their own — real coreutils resolves their Fluent
/// strings from `ls`'s bundle instead (see `uucore::get_canonical_util_name`,
/// which does this same `uu_<name>` → canonical-name mapping for the
/// per-utility binaries in the actual uutils/coreutils monorepo).
fn setup_locale_for(util: &str) {
    let crate_name = UTILS
        .iter()
        .find(|(name, _)| *name == util)
        .map_or(util, |(_, crate_name)| crate_name);
    // Non-uucore-based utilities (e.g. findutils) have no "uu_" prefix to
    // strip and no Fluent locale bundle to look for in the first place.
    if !crate_name.starts_with("uu_") {
        return;
    }
    let canonical = uucore::get_canonical_util_name(crate_name);
    let _ = uucore::locale::setup_localization(canonical);
}

fn main() -> ExitCode {
    // Each `#[uucore::main]`-generated utility already restores SIGPIPE
    // to its default disposition internally, but our own hand-written
    // dispatch targets (tar/gzip/grep/sed/awk/curl/ps/...) don't get
    // that for free — without this, e.g. `coreutils-rs ps aux | head`
    // panics on a broken pipe instead of exiting quietly like every
    // other Unix CLI. Matches pacman-rs's own identical fix.
    unsafe {
        libc::signal(libc::SIGPIPE, libc::SIG_DFL);
    }

    let argv: Vec<OsString> = std::env::args_os().collect();
    let raw_exe_name = argv
        .first()
        .and_then(|a| std::path::Path::new(a).file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("coreutils-rs")
        .to_string();
    // A login shell is conventionally exec'd with argv[0] prefixed with
    // "-" (e.g. `-sh`, `-bash`) — done by `login`, `su - user`, `sudo -i`,
    // display managers, etc. — a signal to the shell itself to behave as
    // a login shell, not a different utility name. Strip it before
    // matching against UTILS so `su - testuser` (whose real shell exec
    // this project's own `su` sets up exactly this way) actually finds
    // our `sh`/`bash` dispatch instead of falling through to the
    // `coreutils-rs <utility>` convention and misreading the shell's own
    // `-c` flag as a utility name. The real argv (still `-sh`) is left
    // untouched for the "sh"/"bash" dispatch arm below, which reads real
    // process argv itself via `brush_shell::entry::run()` and needs the
    // leading `-` to know it's a login shell.
    let exe_name = raw_exe_name
        .strip_prefix('-')
        .unwrap_or(&raw_exe_name)
        .to_string();

    // Symlink form: argv[0] is already the utility name (e.g. `ls`).
    if UTILS.iter().any(|(name, _)| *name == exe_name) {
        setup_locale_for(&exe_name);
        if let Some(code) = dispatch(&exe_name, argv.clone().into_iter()) {
            return exit_code(code);
        }
    }

    // `coreutils-rs <utility> [args...]` form: argv[1] names the utility,
    // and it's handed to the sub-uumain as its own argv[0] so the
    // utility's usage/error messages read as if it were invoked directly.
    let util = argv.get(1).and_then(|a| a.to_str()).map(str::to_string);
    if let Some(util) = util {
        if util == "sh" || util == "bash" {
            return reexec_as(&util, &argv[2..]);
        }
        uucore::set_utility_is_second_arg();
        if UTILS.iter().any(|(name, _)| *name == util) {
            setup_locale_for(&util);
        }
        let sub_argv = argv.into_iter().skip(1).collect::<Vec<_>>().into_iter();
        if let Some(code) = dispatch(&util, sub_argv) {
            return exit_code(code);
        }
        eprintln!("coreutils-rs: unknown utility '{util}'");
        eprintln!("available utilities: {}", utility_names());
        return ExitCode::FAILURE;
    }

    eprintln!("usage: coreutils-rs <utility> [args...]");
    eprintln!("       (or install as a symlink named after the utility)");
    eprintln!("available utilities: {}", utility_names());
    ExitCode::FAILURE
}

fn exit_code(code: i32) -> ExitCode {
    ExitCode::from(code as u8)
}
