//! A busybox/uutils-style multicall binary: reimplementing every individual
//! coreutils command from scratch would just re-derive `uutils/coreutils`,
//! which ROADMAP.md already calls out as prior art to adapt rather than
//! reinvent. So this crate vendors the real `uu_*` crates (the same ones
//! the upstream `coreutils` multicall binary is built from) and supplies
//! only the dispatch logic: pick a utility by name and hand it argv, same
//! as busybox does for its applets.
//!
//! Every `uu_*` crate's public `uumain` is generated by the `#[uucore::main]`
//! attribute macro into `fn(impl uucore::Args) -> i32`, which already
//! prints errors and computes the exit code — there's no `Result` for this
//! binary to unwrap, just an exit code to forward.
//!
//! Two calling conventions, both matching real coreutils/busybox behavior:
//! - as a symlink named after the utility (`ls -> coreutils-rs`, argv[0]
//!   is `ls`) — the common way to actually install this as a system's
//!   userland
//! - as `coreutils-rs <utility> [args...]` — useful for trying it out
//!   without installing symlinks first

use std::ffi::OsString;
use std::process::ExitCode;
use std::vec::IntoIter;

fn dispatch(name: &str, args: IntoIter<OsString>) -> Option<i32> {
    Some(match name {
        "ls" => uu_ls::uumain(args),
        "cat" => uu_cat::uumain(args),
        "cp" => uu_cp::uumain(args),
        "mv" => uu_mv::uumain(args),
        "rm" => uu_rm::uumain(args),
        "mkdir" => uu_mkdir::uumain(args),
        "echo" => uu_echo::uumain(args),
        "pwd" => uu_pwd::uumain(args),
        "touch" => uu_touch::uumain(args),
        "wc" => uu_wc::uumain(args),
        "head" => uu_head::uumain(args),
        "tail" => uu_tail::uumain(args),
        "true" => uu_true::uumain(args),
        "false" => uu_false::uumain(args),
        _ => return None,
    })
}

const UTILITIES: &[&str] = &[
    "ls", "cat", "cp", "mv", "rm", "mkdir", "echo", "pwd", "touch", "wc", "head", "tail", "true",
    "false",
];

fn main() -> ExitCode {
    let argv: Vec<OsString> = std::env::args_os().collect();
    let exe_name = argv
        .first()
        .and_then(|a| std::path::Path::new(a).file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("coreutils-rs")
        .to_string();

    // Symlink form: argv[0] is already the utility name (e.g. `ls`).
    if let Some(code) = dispatch(&exe_name, argv.clone().into_iter()) {
        return exit_code(code);
    }

    // `coreutils-rs <utility> [args...]` form: argv[1] names the utility,
    // and it's handed to the sub-uumain as its own argv[0] so the
    // utility's usage/error messages read as if it were invoked directly.
    let util = argv.get(1).and_then(|a| a.to_str()).map(str::to_string);
    if let Some(util) = util {
        uucore::set_utility_is_second_arg();
        let sub_argv = argv.into_iter().skip(1).collect::<Vec<_>>().into_iter();
        if let Some(code) = dispatch(&util, sub_argv) {
            return exit_code(code);
        }
        eprintln!("coreutils-rs: unknown utility '{util}'");
        eprintln!("available utilities: {}", UTILITIES.join(", "));
        return ExitCode::FAILURE;
    }

    eprintln!("usage: coreutils-rs <utility> [args...]");
    eprintln!("       (or install as a symlink named after the utility)");
    eprintln!("available utilities: {}", UTILITIES.join(", "));
    ExitCode::FAILURE
}

fn exit_code(code: i32) -> ExitCode {
    ExitCode::from(code as u8)
}
